title: John Doe # your name (or website title) here
logo: "/images/headshot_Crop.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Programming</b>
  <br>
  -Unity C#
  -HTML
  <b>Software</b>
  <br>
  -Unity Engine<br>
  -Makehuman<br>
  -Fuse<br>
  -Mixamo
  <br><br>
  <a href="https://www.linkedin.com/in/tomislav-markovic-71b0aaa2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
