title: Tomislav Markovic # your name (or website title) here
logo: "/images/headshot_Crop.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Personal Info</b><br>
  Birth: 16th of November, 1986 <br>
  Email: markovictomislav1@gmail.com
  <br>
  Phone Number: +385922273710
  <br>
  <br>
  <a href="https://shadowh86.github.io/resume">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/tomislav-markovic-71b0aaa2/">LinkedIn Profile</a>
  <br>
  <a href="https://thedynamitepriest.itch.io/">Itch.io Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

